services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sandeeptiwari-portfolio
    ports:
      - "3000:3000"
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_GITHUB_TOKEN=${REACT_APP_GITHUB_TOKEN:-}
    stdin_open: true
    tty: true
